name: CI_pipeline
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI_jobs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    permissions:
      contents: read
      id-token: write # Needed to request OIDC token from GitHub
      statuses: write # To report GitHub Actions status checks

    env:
      GITHUB_PR_SCHEMA: ${{ github.event.number }}
      GITHUB_LAST_COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      GCP_LOCATION: ${{secrets.GCP_LOCATION}}
      GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
      GCP_REPOSITORY: ${{secrets.GCP_REPOSITORY}}
      GCP_CLOUD_RUN_SERVICE_NAME: ${{secrets.GCP_CLOUD_RUN_SERVICE_NAME}}
      IMAGE_NAME: ${{secrets.IMAGE_NAME}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changed Files
        id: file_changes
        uses: tj-actions/changed-files@v46.0.3

      - name: Changed Files in src
        id: src_changes
        uses: tj-actions/changed-files@v46.0.3
        with:
          files: |
            src/**

      - name: Print info
        run: |
          echo Event name: ${{ github.event_name }}
          echo PR number: "$GITHUB_PR_SCHEMA"
          echo last commit sha: "$GITHUB_LAST_COMMIT_SHA"
          echo Changed files: '${{ steps.file_changes.outputs.all_changed_files}}'
          echo Has changes in src/ files: '${{ steps.src_changes.outputs.any_changed }}'

      - name: Run pre-commit on changed files
        if: steps.file_changes.outputs.any_changed == 'true'
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.file_changes.outputs.all_changed_files }}

      - name: Authenticate to Google Cloud with Workload Identity Federation
        id: auth_gcloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/264268171873/locations/global/workloadIdentityPools/elif-github-actions-pool/providers/github-provider'
          service_account: ${{secrets.GCP_WIF_SA}}
          token_format: 'access_token'  # Outputs access_token

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Docker auth to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.GCP_LOCATION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth_gcloud.outputs.access_token }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GCP_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Print short sha tag
        run: echo "Tag is ${{ steps.meta.outputs.version }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        if: steps.src_changes.outputs.any_changed == 'true'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Decide which tag Terraform should deploy:
      # - If src changed: use the new sha tag from metadata
      # - If not: resolve the latest existing tag from Artifact Registry
      - name: Resolve image tag to deploy
        id: resolve_tag
        run: |
          if [ "${{ steps.src_changes.outputs.any_changed }}" = "true" ]; then
            echo "IMAGE_TAG=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV
            echo "Using new image tag from sha."
          else
            echo "No src changes; resolving latest existing image tag..."
            IMAGE_PATH="${{ env.GCP_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ env.IMAGE_NAME }}"
            LATEST_TAG=$(gcloud artifacts docker tags list "$IMAGE_PATH" \
              --location="${{ env.GCP_LOCATION }}" \
              --format="value(tag, updateTime)"  \
              --sort-by="~updateTime" | head -n 1 | awk '{print $1}')
            if [ -z "$LATEST_TAG" ]; then
              echo "No tags found in Artifact Registry; defaulting to <latest> tag."
              LATEST_TAG="latest"
            fi
            echo "IMAGE_TAG=$LATEST_TAG" >> $GITHUB_ENV
            echo "Resolved IMAGE_TAG=$LATEST_TAG"
          fi

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        env:
          TF_STATE_BUCKET: ${{secrets.TF_STATE_BUCKET}}
          TF_STATE_BUCKET_PREFIX: "env/dev/terraform/state"
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="prefix=${{env.TF_STATE_BUCKET_PREFIX}}"

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          TF_VAR_gcp_sa_email: ${{secrets.GCP_WIF_SA}}
          TF_VAR_db_user: ${{secrets.GCP_PG_DB_USER}}
          TF_VAR_db_password: ${{secrets.GCP_PG_DB_PWD}}
          TF_VAR_cache_enabled: "False"
          TF_VAR_db_port: 5432
          TF_VAR_db_name: "easyconvert"
          TF_VAR_artifact_reg_repo: ${{env.GCP_REPOSITORY}}
          TF_VAR_artifact_image_name: ${{env.IMAGE_NAME}}
          TF_VAR_artifact_image_tag: ${{ env.IMAGE_TAG }}
          TF_VAR_cloud_run_proxy_port: 8000
          TF_VAR_cloud_run_service_name: ${{env.GCP_CLOUD_RUN_SERVICE_NAME}}
        run: |
          terraform plan -no-color -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_gcp_sa_email: ${{secrets.GCP_WIF_SA}}
          TF_VAR_db_user: ${{secrets.GCP_PG_DB_USER}}
          TF_VAR_db_password: ${{secrets.GCP_PG_DB_PWD}}
          TF_VAR_cache_enabled: "False"
          TF_VAR_db_port: 5432
          TF_VAR_db_name: "easyconvert"
          TF_VAR_artifact_reg_repo: ${{env.GCP_REPOSITORY}}
          TF_VAR_artifact_image_name: ${{env.IMAGE_NAME}}
          TF_VAR_artifact_image_tag: ${{ env.IMAGE_TAG }}
          TF_VAR_cloud_run_proxy_port: 8000
          TF_VAR_cloud_run_service_name: ${{env.GCP_CLOUD_RUN_SERVICE_NAME}}
        run: |
          terraform apply -auto-approve -input=false
