name: CI_pipeline
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI_jobs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    permissions:
      contents: read
      id-token: write # Needed to request OIDC token from GitHub
      statuses: write # To report GitHub Actions status checks

    env:
      GITHUB_PR_SCHEMA: ${{ github.event.number }}
      GITHUB_LAST_COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      GCP_LOCATION: ${{secrets.GCP_LOCATION}}
      GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
      GCP_REPOSITORY: ${{secrets.GCP_REPOSITORY}}
      GCP_CLOUD_RUN_SERVICE_NAME: ${{secrets.GCP_CLOUD_RUN_SERVICE_NAME}}
      IMAGE_NAME: ${{secrets.IMAGE_NAME}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changed Files
        id: file_changes
        uses: tj-actions/changed-files@v46.0.3

      - name: Print info
        run: |
          echo Event name: ${{ github.event_name }}
          echo PR number: "$GITHUB_PR_SCHEMA"
          echo last commit sha: "$GITHUB_LAST_COMMIT_SHA"
          echo Changed files: '${{ steps.file_changes.outputs.all_changed_files}}'

      - name: Run pre-commit on changed files
        if: steps.file_changes.outputs.any_changed == 'true'
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.file_changes.outputs.all_changed_files }}

      - name: Authenticate to Google Cloud with Workload Identity Federation
        id: auth_gcloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/264268171873/locations/global/workloadIdentityPools/elif-github-actions-pool/providers/github-provider'
          service_account: elif-github-actions-sa@ae-terraform-2025.iam.gserviceaccount.com
          token_format: 'access_token'  # Outputs access_token

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Docker auth to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.GCP_LOCATION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth_gcloud.outputs.access_token }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GCP_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
